import type {
  User,
  Professional,
  Client,
  ServiceConfig,
  Product,
  Appointment,
  Transaction,
  CashRegister,
  Settlement,
  ServicePack,
  ProductPurchase,
  ProductSale,
  Supplier,
  MedicalRecord,
  KinesiologyEvaluation,
  KinesiologyTreatment,
  KineHomeProgram,
  TrainingEvaluation,
  TrainingRoutine,
  ClinicalEvolution,
  MedicalMedia,
  PatientDailyLog,
  PatientTask,
  ChatConversation,
  ChatMessage,
  StaffGoal,
} from "./types"

export const currentUser: User = {
  id: "user-1",
  email: "tense.kinesio@gmail.com",
  name: "TENSE GOOD",
  role: "super_admin",
  status: "active",
  createdAt: new Date("2024-01-01"),
}

export const users: User[] = [
  currentUser,
  {
    id: "user-2",
    email: "recepcion.tense@gmail.com",
    name: "Recepción Tense",
    role: "admin",
    status: "active",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "user-prof-1",
    email: "roberto@tense.com",
    name: "Dr. Roberto Fernández",
    role: "profesional",
    status: "active",
    professionalId: "prof-1",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "user-prof-2",
    email: "maria@tense.com",
    name: "Lic. María Gómez",
    role: "profesional",
    status: "active",
    professionalId: "prof-2",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "user-3",
    email: "cliente@email.com",
    name: "Ana Martínez",
    role: "cliente",
    status: "active",
    clientId: "client-ana",
    createdAt: new Date("2024-02-01"),
  },
]

export const serviceConfigs: ServiceConfig[] = [
  {
    id: "service-1",
    name: "Kinesiología",
    description: "Sesión de kinesiología y rehabilitación",
    basePrice: 6000,
    standardDuration: 45,
    professionalPercentage: 65,
    requiresDeposit: true,
    recommendedDepositPercentage: 50,
    isActive: true,
    color: "violet",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "service-2",
    name: "Entrenamiento Personalizado",
    description: "Sesión de entrenamiento individual",
    basePrice: 4300,
    standardDuration: 60,
    professionalPercentage: 60,
    requiresDeposit: true,
    recommendedDepositPercentage: 50,
    isActive: true,
    color: "green",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "service-3",
    name: "Antropometría",
    description: "Evaluación antropométrica completa",
    basePrice: 15000,
    standardDuration: 90,
    professionalPercentage: 50,
    requiresDeposit: true,
    recommendedDepositPercentage: 50,
    isActive: true,
    color: "amber",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "service-4",
    name: "Masajes",
    description: "Sesión de masajes descontracturantes",
    basePrice: 10000,
    standardDuration: 60,
    professionalPercentage: 55,
    requiresDeposit: false,
    recommendedDepositPercentage: 0,
    isActive: true,
    color: "indigo",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const suppliers: Supplier[] = [
  {
    id: "supplier-1",
    name: "Aguas del Litoral",
    contactName: "Carlos Pérez",
    email: "ventas@aguaslitoral.com",
    phone: "+54 11 4567-8901",
    address: "Av. Corrientes 1234, CABA",
    notes: "Proveedor de bebidas",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "supplier-2",
    name: "NutriFit",
    contactName: "Laura Gómez",
    email: "pedidos@nutrifit.com",
    phone: "+54 11 5678-9012",
    address: "Av. Santa Fe 4567, CABA",
    notes: "Suplementos deportivos",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "supplier-3",
    name: "Snack&Go",
    contactName: "Martín López",
    email: "contacto@snackgo.com",
    phone: "+54 11 6789-0123",
    address: "Av. Cabildo 789, CABA",
    notes: "Snacks y barritas",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
]

export const products: Product[] = [
  {
    id: "prod-1",
    name: "Agua Mineral 500ml",
    category: "Bebidas",
    costPrice: 180, // Último precio promedio
    salePrice: 300,
    currentStock: 88, // 40 + 50 - 2 (venta)
    minimumStock: 10,
    stockMinimo: 10,
    stockMedio: 20,
    supplier: "Aguas del Litoral",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-2",
    name: "Proteína Whey 1kg",
    category: "Suplementos",
    costPrice: 8750, // Promedio de 8500 y 9000
    salePrice: 15000,
    currentStock: 14, // 10 + 5 - 1 (venta)
    minimumStock: 3,
    stockMinimo: 3,
    stockMedio: 6,
    supplier: "NutriFit",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-3",
    name: "Barrita Proteica",
    category: "Snacks",
    costPrice: 300, // Último precio promedio
    salePrice: 600,
    currentStock: 97, // 60 + 40 - 3 (venta)
    minimumStock: 15,
    stockMinimo: 15,
    stockMedio: 30,
    supplier: "Snack&Go",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-4",
    name: "Bebida Isotónica 750ml",
    category: "Bebidas",
    costPrice: 600,
    salePrice: 1000,
    currentStock: 18,
    minimumStock: 10,
    stockMinimo: 10,
    stockMedio: 20,
    supplier: "Aguas del Litoral",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
]

export const productPurchases: ProductPurchase[] = [
  // Agua mineral 500ml
  {
    id: "purchase-1",
    productId: "prod-1",
    supplierId: "supplier-1",
    quantity: 40,
    unitCost: 160,
    totalCost: 6400,
    date: new Date("2025-10-05"),
    invoiceNumber: "FA-001-00012345",
    notes: "Primera compra octubre",
    createdAt: new Date("2025-10-05"),
  },
  {
    id: "purchase-2",
    productId: "prod-1",
    supplierId: "supplier-1",
    quantity: 50,
    unitCost: 180,
    totalCost: 9000,
    date: new Date("2025-10-20"),
    invoiceNumber: "FA-001-00012456",
    notes: "Segunda compra octubre - precio actualizado",
    createdAt: new Date("2025-10-20"),
  },
  // Proteína Whey 1kg
  {
    id: "purchase-3",
    productId: "prod-2",
    supplierId: "supplier-2",
    quantity: 10,
    unitCost: 8500,
    totalCost: 85000,
    date: new Date("2025-10-08"),
    invoiceNumber: "FA-002-00005678",
    notes: "Stock inicial octubre",
    createdAt: new Date("2025-10-08"),
  },
  {
    id: "purchase-4",
    productId: "prod-2",
    supplierId: "supplier-2",
    quantity: 5,
    unitCost: 9000,
    totalCost: 45000,
    date: new Date("2025-10-22"),
    invoiceNumber: "FA-002-00005789",
    notes: "Reposición - aumento de precio",
    createdAt: new Date("2025-10-22"),
  },
  // Barrita proteica
  {
    id: "purchase-5",
    productId: "prod-3",
    supplierId: "supplier-3",
    quantity: 60,
    unitCost: 280,
    totalCost: 16800,
    date: new Date("2025-10-10"),
    invoiceNumber: "FA-003-00003456",
    notes: "Compra inicial barritas",
    createdAt: new Date("2025-10-10"),
  },
  {
    id: "purchase-6",
    productId: "prod-3",
    supplierId: "supplier-3",
    quantity: 40,
    unitCost: 300,
    totalCost: 12000,
    date: new Date("2025-10-25"),
    invoiceNumber: "FA-003-00003567",
    notes: "Reposición octubre",
    createdAt: new Date("2025-10-25"),
  },
]

export const professionals: Professional[] = [
  {
    id: "prof-1",
    name: "Dr. Roberto Fernández",
    email: "roberto@tense.com",
    phone: "+54 11 1234-5678",
    specialty: "Entrenamiento Personalizado",
    workingHours: { start: "09:00", end: "18:00" },
    standardDuration: 60,
    nonWorkingDays: [0, 6],
    services: ["service-2", "service-4"],
    commissionRate: 60, // El profesional recibe 60%, TENSE cobra 40%
    isActive: true,
    status: "active",
    availability: {
      slotDuration: 60,
      schedule: [
        { dayOfWeek: 0, isActive: false, slots: [] },
        {
          dayOfWeek: 1,
          isActive: true,
          slots: [
            { start: "09:00", end: "10:00" },
            { start: "10:00", end: "11:00" },
            { start: "11:00", end: "12:00" },
            { start: "14:00", end: "15:00" },
            { start: "15:00", end: "16:00" },
            { start: "16:00", end: "17:00" },
            { start: "17:00", end: "18:00" },
          ],
        },
        {
          dayOfWeek: 2,
          isActive: true,
          slots: [
            { start: "09:00", end: "10:00" },
            { start: "10:00", end: "11:00" },
            { start: "11:00", end: "12:00" },
            { start: "14:00", end: "15:00" },
            { start: "15:00", end: "16:00" },
            { start: "16:00", end: "17:00" },
          ],
        },
        {
          dayOfWeek: 3,
          isActive: true,
          slots: [
            { start: "09:00", end: "10:00" },
            { start: "10:00", end: "11:00" },
            { start: "11:00", end: "12:00" },
            { start: "14:00", end: "15:00" },
            { start: "15:00", end: "16:00" },
            { start: "16:00", end: "17:00" },
          ],
        },
        {
          dayOfWeek: 4,
          isActive: true,
          slots: [
            { start: "09:00", end: "10:00" },
            { start: "10:00", end: "11:00" },
            { start: "11:00", end: "12:00" },
            { start: "14:00", end: "15:00" },
            { start: "15:00", end: "16:00" },
          ],
        },
        {
          dayOfWeek: 5,
          isActive: true,
          slots: [
            { start: "09:00", end: "10:00" },
            { start: "10:00", end: "11:00" },
            { start: "11:00", end: "12:00" },
          ],
        },
        { dayOfWeek: 6, isActive: false, slots: [] },
      ],
    },
  },
  {
    id: "prof-2",
    name: "Lic. María Gómez",
    email: "maria@tense.com",
    phone: "+54 11 2345-6789",
    specialty: "Kinesiología",
    workingHours: { start: "10:00", end: "19:00" },
    standardDuration: 45,
    nonWorkingDays: [0],
    services: ["service-1", "service-3"],
    commissionRate: 65, // El profesional recibe 65%, TENSE cobra 35%
    isActive: true,
    status: "active",
    availability: {
      slotDuration: 45,
      schedule: [
        { dayOfWeek: 0, isActive: false, slots: [] },
        {
          dayOfWeek: 1,
          isActive: true,
          slots: [
            { start: "10:00", end: "10:45" },
            { start: "10:45", end: "11:30" },
            { start: "11:30", end: "12:15" },
            { start: "14:00", end: "14:45" },
            { start: "14:45", end: "15:30" },
            { start: "15:30", end: "16:15" },
            { start: "16:00", end: "16:45" },
            { start: "17:00", end: "17:45" },
          ],
        },
        {
          dayOfWeek: 2,
          isActive: true,
          slots: [
            { start: "10:00", end: "10:45" },
            { start: "10:45", end: "11:30" },
            { start: "14:00", end: "14:45" },
            { start: "14:45", end: "15:30" },
          ],
        },
        {
          dayOfWeek: 3,
          isActive: true,
          slots: [
            { start: "10:00", end: "10:45" },
            { start: "10:45", end: "11:30" },
            { start: "11:30", end: "12:15" },
            { start: "14:00", end: "15:00" },
            { start: "15:00", end: "16:00" },
            { start: "16:15", end: "17:00" },
          ],
        },
        {
          dayOfWeek: 4,
          isActive: true,
          slots: [
            { start: "10:00", end: "10:45" },
            { start: "14:00", end: "14:45" },
            { start: "14:45", end: "15:30" },
          ],
        },
        {
          dayOfWeek: 5,
          isActive: true,
          slots: [
            { start: "10:00", end: "10:45" },
            { start: "10:45", end: "11:30" },
          ],
        },
        {
          dayOfWeek: 6,
          isActive: true,
          slots: [
            { start: "10:00", end: "10:45" },
            { start: "10:45", end: "11:30" },
          ],
        },
      ],
    },
  },
  {
    id: "prof-3",
    name: "Lic. Miguel Torres",
    email: "miguel@tense.com",
    phone: "+54 11 3456-7890",
    specialty: "Masajes",
    workingHours: { start: "08:00", end: "16:00" },
    standardDuration: 60,
    nonWorkingDays: [0, 6],
    services: ["service-4", "service-3"],
    commissionRate: 55, // El profesional recibe 55%, TENSE cobra 45%
    isActive: true,
    status: "active",
    availability: {
      slotDuration: 60,
      schedule: [
        { dayOfWeek: 0, isActive: false, slots: [] },
        {
          dayOfWeek: 1,
          isActive: true,
          slots: [
            { start: "08:00", end: "09:00" },
            { start: "09:00", end: "10:00" },
            { start: "10:00", end: "11:00" },
            { start: "14:00", end: "15:00" },
            { start: "15:00", end: "16:00" },
          ],
        },
        {
          dayOfWeek: 2,
          isActive: true,
          slots: [
            { start: "08:00", end: "09:00" },
            { start: "09:00", end: "10:00" },
            { start: "14:00", end: "15:00" },
          ],
        },
        {
          dayOfWeek: 3,
          isActive: true,
          slots: [
            { start: "08:00", end: "09:00" },
            { start: "09:00", end: "10:00" },
            { start: "10:00", end: "11:00" },
            { start: "11:00", end: "12:00" },
            { start: "14:00", end: "15:00" },
            { start: "15:00", end: "16:00" },
          ],
        },
        {
          dayOfWeek: 4,
          isActive: true,
          slots: [
            { start: "09:00", end: "10:00" },
            { start: "10:00", end: "11:00" },
          ],
        },
        {
          dayOfWeek: 5,
          isActive: true,
          slots: [
            { start: "08:00", end: "09:00" },
            { start: "09:00", end: "10:00" },
            { start: "10:00", end: "11:00" },
          ],
        },
        { dayOfWeek: 6, isActive: false, slots: [] },
      ],
    },
  },
]

export const clients: Client[] = [
  {
    id: "client-1",
    name: "Ramiro González",
    dni: "53682423",
    email: "ramiro@gmail.com",
    phone: "1127033633",
    notes: "Prefiere turnos por la mañana",
    balance: 0,
    specialDiscount: 0,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "client-2",
    name: "Carla Méndez",
    dni: "34567890",
    email: "carla@email.com",
    phone: "+54 11 5678-9012",
    notes: "",
    balance: 0,
    specialDiscount: 0,
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "client-3",
    name: "Juan Pérez",
    dni: "28901234",
    email: "juan@email.com",
    phone: "+54 11 6789-0123",
    notes: "Historial de inasistencias",
    balance: 0,
    specialDiscount: 0,
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "client-4",
    name: "Ana López",
    dni: "31234567",
    email: "ana@email.com",
    phone: "+54 11 7890-1234",
    notes: "",
    balance: 0,
    specialDiscount: 0,
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "client-5",
    name: "Pedro Díaz",
    dni: "29876543",
    email: "pedro@email.com",
    phone: "+54 11 8901-2345",
    notes: "",
    balance: 0,
    specialDiscount: 0,
    createdAt: new Date("2024-04-01"),
  },
  {
    id: "client-ana",
    name: "Ana Martínez",
    dni: "32456789",
    email: "cliente@email.com",
    phone: "+54 11 9012-3456",
    notes: "Usuario registrado en el sistema",
    balance: 0,
    specialDiscount: 0,
    createdAt: new Date("2024-02-01"),
  },
]

export const appointments: Appointment[] = [
  // ========== DR. ROBERTO FERNÁNDEZ - 05/11/2025 ==========
  // Turno 10:00 - Ramiro González - ASISTIÓ
  {
    id: "apt-nov-1",
    professionalId: "prof-1",
    clientId: "client-1",
    serviceId: "service-2",
    date: new Date("2025-11-05"),
    startTime: "10:00",
    endTime: "11:00",
    basePrice: 4300,
    discountPercent: 0,
    finalPrice: 4300,
    professionalPercentage: 60,
    professionalEarnings: 2580, // 60% de 4300
    recommendedDeposit: 2150,
    depositAmount: 2150,
    isDepositComplete: true,
    paidAmount: 4300,
    payments: [
      {
        id: "pay-nov-1a",
        amount: 2150,
        paymentMethod: "cash",
        receivedByProfessionalId: "prof-1",
        isDeposit: true,
        paymentDate: new Date("2025-11-04"),
        createdAt: new Date("2025-11-04"),
        notes: "Seña previa - efectivo en Caja TENSE profesional",
      },
      {
        id: "pay-nov-1b",
        amount: 2150,
        paymentMethod: "transfer",
        receivedByProfessionalId: "prof-1",
        isDeposit: false,
        paymentDate: new Date("2025-11-05"),
        createdAt: new Date("2025-11-05"),
        notes: "Saldo - transferencia directa al profesional",
      },
    ],
    status: "attended",
    isPaid: true,
    cashCollected: 2150,
    transferCollected: 2150,
    cashInTense: 2150,
    transfersToProfessional: 2150,
    notes: "",
    comments: [],
    createdAt: new Date("2025-11-03"),
  },
  // Turno 11:00 - Carla Méndez - ASISTIÓ
  {
    id: "apt-nov-2",
    professionalId: "prof-1",
    clientId: "client-2",
    serviceId: "service-2",
    date: new Date("2025-11-05"),
    startTime: "11:00",
    endTime: "12:00",
    basePrice: 4300,
    discountPercent: 0,
    finalPrice: 4300,
    professionalPercentage: 60,
    professionalEarnings: 2580,
    recommendedDeposit: 2150,
    depositAmount: 0,
    isDepositComplete: false,
    paidAmount: 4300,
    payments: [
      {
        id: "pay-nov-2",
        amount: 4300,
        paymentMethod: "cash",
        receivedByProfessionalId: "prof-1",
        isDeposit: false,
        paymentDate: new Date("2025-11-05"),
        createdAt: new Date("2025-11-05"),
        notes: "Pago completo en efectivo - Caja TENSE profesional",
      },
    ],
    status: "attended",
    isPaid: true,
    cashCollected: 4300,
    transferCollected: 0,
    cashInTense: 4300,
    transfersToProfessional: 0,
    notes: "",
    comments: [],
    createdAt: new Date("2025-11-04"),
  },
  // Turno 12:00 - Juan Pérez - NO ASISTIÓ
  {
    id: "apt-nov-3",
    professionalId: "prof-1",
    clientId: "client-3",
    serviceId: "service-2",
    date: new Date("2025-11-05"),
    startTime: "12:00",
    endTime: "13:00",
    basePrice: 4300,
    discountPercent: 0,
    finalPrice: 4300,
    professionalPercentage: 60,
    professionalEarnings: 2580,
    recommendedDeposit: 2150,
    depositAmount: 2150,
    isDepositComplete: true,
    paidAmount: 2150,
    payments: [
      {
        id: "pay-nov-3",
        amount: 2150,
        paymentMethod: "cash",
        receivedByProfessionalId: "prof-1",
        isDeposit: true,
        paymentDate: new Date("2025-11-04"),
        createdAt: new Date("2025-11-04"),
        notes: "Seña previa - queda para el profesional por NO ASISTIÓ",
      },
    ],
    status: "no_show",
    isPaid: false,
    cashCollected: 2150,
    transferCollected: 0,
    cashInTense: 2150, // La seña queda en caja TENSE pero es del profesional
    transfersToProfessional: 0,
    notes: "No se presentó ni avisó - seña queda para el profesional",
    comments: [],
    createdAt: new Date("2025-11-03"),
  },

  // ========== LIC. MARÍA GÓMEZ - 05/11/2025 ==========
  // Turno 16:00 - Ana López - ASISTIÓ
  {
    id: "apt-nov-4",
    professionalId: "prof-2",
    clientId: "client-4",
    serviceId: "service-1",
    date: new Date("2025-11-05"),
    startTime: "16:00",
    endTime: "16:45",
    basePrice: 6000,
    discountPercent: 0,
    finalPrice: 6000,
    professionalPercentage: 65,
    professionalEarnings: 3900, // 65% de 6000
    recommendedDeposit: 3000,
    depositAmount: 3000,
    isDepositComplete: true,
    paidAmount: 6000,
    payments: [
      {
        id: "pay-nov-4a",
        amount: 3000,
        paymentMethod: "cash",
        receivedByProfessionalId: "prof-2",
        isDeposit: false,
        paymentDate: new Date("2025-11-05"),
        createdAt: new Date("2025-11-05"),
        notes: "Pago parcial efectivo - Caja TENSE profesional",
      },
      {
        id: "pay-nov-4b",
        amount: 3000,
        paymentMethod: "transfer",
        receivedByProfessionalId: "prof-2",
        isDeposit: false,
        paymentDate: new Date("2025-11-05"),
        createdAt: new Date("2025-11-05"),
        notes: "Pago parcial transferencia al profesional",
      },
    ],
    status: "attended",
    isPaid: true,
    cashCollected: 3000,
    transferCollected: 3000,
    cashInTense: 3000,
    transfersToProfessional: 3000,
    notes: "",
    comments: [],
    createdAt: new Date("2025-11-04"),
  },
  // Turno 17:00 - Pedro Díaz - CONFIRMADO (solo seña)
  {
    id: "apt-nov-5",
    professionalId: "prof-2",
    clientId: "client-5",
    serviceId: "service-1",
    date: new Date("2025-11-05"),
    startTime: "17:00",
    endTime: "17:45",
    basePrice: 6000,
    discountPercent: 0,
    finalPrice: 6000,
    professionalPercentage: 65,
    professionalEarnings: 3900,
    recommendedDeposit: 3000,
    depositAmount: 3000,
    isDepositComplete: true,
    paidAmount: 3000,
    payments: [
      {
        id: "pay-nov-5",
        amount: 3000,
        paymentMethod: "cash",
        receivedByProfessionalId: "prof-2",
        isDeposit: true,
        paymentDate: new Date("2025-11-04"),
        createdAt: new Date("2025-11-04"),
        notes: "Seña - Caja TENSE profesional",
      },
    ],
    status: "confirmed",
    isPaid: false,
    cashCollected: 3000,
    transferCollected: 0,
    cashInTense: 3000,
    transfersToProfessional: 0,
    notes: "",
    comments: [],
    createdAt: new Date("2025-11-03"),
  },

  // ========== TURNOS ADICIONALES OCTUBRE/NOVIEMBRE 2025 ==========
  // Para completar datos históricos
  {
    id: "apt-oct-1",
    professionalId: "prof-1",
    clientId: "client-1",
    serviceId: "service-2",
    date: new Date("2025-10-15"),
    startTime: "10:00",
    endTime: "11:00",
    basePrice: 4300,
    discountPercent: 0,
    finalPrice: 4300,
    professionalPercentage: 60,
    professionalEarnings: 2580,
    recommendedDeposit: 2150,
    depositAmount: 2150,
    isDepositComplete: true,
    paidAmount: 4300,
    payments: [
      {
        id: "pay-oct-1a",
        amount: 2150,
        paymentMethod: "cash",
        receivedByProfessionalId: "prof-1",
        isDeposit: true,
        paymentDate: new Date("2025-10-14"),
        createdAt: new Date("2025-10-14"),
        notes: "Seña",
      },
      {
        id: "pay-oct-1b",
        amount: 2150,
        paymentMethod: "cash",
        receivedByProfessionalId: "prof-1",
        isDeposit: false,
        paymentDate: new Date("2025-10-15"),
        createdAt: new Date("2025-10-15"),
        notes: "Saldo",
      },
    ],
    status: "attended",
    isPaid: true,
    cashCollected: 4300,
    transferCollected: 0,
    cashInTense: 4300,
    transfersToProfessional: 0,
    notes: "",
    comments: [],
    createdAt: new Date("2025-10-13"),
  },
  {
    id: "apt-oct-2",
    professionalId: "prof-2",
    clientId: "client-4",
    serviceId: "service-1",
    date: new Date("2025-10-20"),
    startTime: "14:00",
    endTime: "14:45",
    basePrice: 6000,
    discountPercent: 0,
    finalPrice: 6000,
    professionalPercentage: 65,
    professionalEarnings: 3900,
    recommendedDeposit: 3000,
    depositAmount: 3000,
    isDepositComplete: true,
    paidAmount: 6000,
    payments: [
      {
        id: "pay-oct-2a",
        amount: 3000,
        paymentMethod: "cash",
        receivedByProfessionalId: "prof-2",
        isDeposit: true,
        paymentDate: new Date("2025-10-19"),
        createdAt: new Date("2025-10-19"),
        notes: "Seña",
      },
      {
        id: "pay-oct-2b",
        amount: 3000,
        paymentMethod: "transfer",
        receivedByProfessionalId: "prof-2",
        isDeposit: false,
        paymentDate: new Date("2025-10-20"),
        createdAt: new Date("2025-10-20"),
        notes: "Saldo",
      },
    ],
    status: "attended",
    isPaid: true,
    cashCollected: 3000,
    transferCollected: 3000,
    cashInTense: 3000,
    transfersToProfessional: 3000,
    notes: "",
    comments: [],
    createdAt: new Date("2025-10-18"),
  },
]

export const productSales: ProductSale[] = [
  // Venta VP-001 - Agua 500ml x 2 - EFECTIVO
  {
    id: "sale-nov-1",
    items: [{ productId: "prod-1", quantity: 2, unitPrice: 300, subtotal: 600 }],
    totalAmount: 600,
    paymentMethod: "cash",
    clientId: undefined,
    notes: "Venta múltiple",
    date: new Date("2025-10-15"),
    createdAt: new Date("2025-10-15T14:00:00"),
  },
  // Venta VP-002 - Barrita proteica x 3 - EFECTIVO
  {
    id: "sale-nov-2",
    items: [{ productId: "prod-3", quantity: 3, unitPrice: 600, subtotal: 1800 }],
    totalAmount: 1800,
    paymentMethod: "cash",
    clientId: "client-1",
    notes: "Venta de proteína a Ramiro",
    date: new Date("2024-04-10"),
    createdAt: new Date("2024-04-10"),
  },
  // Venta VP-003 - Proteína Whey 1kg - TRANSFERENCIA
  {
    id: "sale-nov-3",
    items: [{ productId: "prod-2", quantity: 1, unitPrice: 15000, subtotal: 15000 }],
    totalAmount: 15000,
    paymentMethod: "transfer",
    clientId: "client-1",
    notes: "Ramiro González - Transferencia a cuenta TENSE Administrador",
    date: new Date("2025-11-05"),
    createdAt: new Date("2025-11-05T11:00:00"),
  },
  // Ventas adicionales de octubre para historial
  {
    id: "sale-oct-1",
    items: [
      { productId: "prod-1", quantity: 5, unitPrice: 300, subtotal: 1500 },
      { productId: "prod-3", quantity: 2, unitPrice: 600, subtotal: 1200 },
    ],
    totalAmount: 2700,
    paymentMethod: "cash",
    clientId: undefined,
    notes: "Compra de barrita proteica por Ana Martínez",
    date: new Date("2024-10-15"),
    createdAt: new Date("2024-10-15"),
  },
  {
    id: "sale-oct-2",
    items: [{ productId: "prod-4", quantity: 3, unitPrice: 1000, subtotal: 3000 }],
    totalAmount: 3000,
    paymentMethod: "cash",
    clientId: undefined,
    notes: "Venta de agua a cliente casual",
    date: new Date("2024-03-25"),
    createdAt: new Date("2024-03-25"),
  },
  {
    id: "sale-5",
    items: [{ productId: "prod-3", quantity: 2, unitPrice: 600, subtotal: 1200 }],
    totalAmount: 1200,
    paymentMethod: "cash",
    notes: "Venta de barritas",
    date: new Date("2024-10-20"),
    createdAt: new Date("2024-10-20"),
  },
]

export const transactions: Transaction[] = [
  // ========== TRANSACCIONES 05/11/2025 - DR. ROBERTO FERNÁNDEZ ==========
  {
    id: "txn-nov-1",
    date: new Date("2025-11-04"),
    type: "deposit_payment",
    amount: 2150,
    paymentMethod: "cash",
    cashRegisterType: "professional",
    professionalId: "prof-1",
    appointmentId: "apt-nov-1",
    clientId: "client-1",
    notes: "Seña Ramiro González - turno 05/11 10:00",
    createdAt: new Date("2025-11-04"),
  },
  {
    id: "txn-nov-2",
    date: new Date("2025-11-05"),
    type: "session_payment",
    amount: 4300,
    paymentMethod: "cash",
    cashRegisterType: "professional",
    professionalId: "prof-1",
    appointmentId: "apt-nov-2",
    clientId: "client-2",
    notes: "Pago completo Carla Méndez - turno 05/11 11:00",
    createdAt: new Date("2025-11-05"),
  },
  {
    id: "txn-nov-3",
    date: new Date("2025-11-04"),
    type: "deposit_payment",
    amount: 2150,
    paymentMethod: "cash",
    cashRegisterType: "professional",
    professionalId: "prof-1",
    appointmentId: "apt-nov-3",
    clientId: "client-3",
    notes: "Seña Juan Pérez (NO ASISTIÓ) - queda para profesional",
    createdAt: new Date("2025-11-04"),
  },

  // ========== TRANSACCIONES 05/11/2025 - LIC. MARÍA GÓMEZ ==========
  {
    id: "txn-nov-4",
    date: new Date("2025-11-05"),
    type: "session_payment",
    amount: 3000,
    paymentMethod: "cash",
    cashRegisterType: "professional",
    professionalId: "prof-2",
    appointmentId: "apt-nov-4",
    clientId: "client-4",
    notes: "Pago parcial efectivo Ana López",
    createdAt: new Date("2025-11-05"),
  },
  {
    id: "txn-nov-5",
    date: new Date("2025-11-04"),
    type: "deposit_payment",
    amount: 3000,
    paymentMethod: "cash",
    cashRegisterType: "professional",
    professionalId: "prof-2",
    appointmentId: "apt-nov-5",
    clientId: "client-5",
    notes: "Seña Pedro Díaz - turno 05/11 17:00",
    createdAt: new Date("2025-11-04"),
  },

  // ========== TRANSACCIONES VENTAS PRODUCTOS 05/11/2025 ==========
  {
    id: "txn-sale-1",
    date: new Date("2025-11-05"),
    type: "product_sale",
    amount: 600,
    paymentMethod: "cash",
    cashRegisterType: "reception",
    notes: "Venta Agua 500ml x 2",
    createdAt: new Date("2025-11-05T10:30:00"),
  },
  {
    id: "txn-sale-2",
    date: new Date("2025-11-05"),
    type: "product_sale",
    amount: 1800,
    paymentMethod: "cash",
    cashRegisterType: "reception",
    clientId: "client-2",
    notes: "Venta Barrita proteica x 3 - Carla Méndez",
    createdAt: new Date("2025-11-05T12:15:00"),
  },
  {
    id: "txn-sale-3",
    date: new Date("2025-11-05"),
    type: "product_sale",
    amount: 15000,
    paymentMethod: "transfer",
    cashRegisterType: "administrator",
    clientId: "client-1",
    notes: "Venta Proteína Whey 1kg - Ramiro González - Transferencia",
    createdAt: new Date("2025-11-05T11:00:00"),
  },
]

export const cashRegisters: CashRegister[] = [
  {
    id: "cash-admin",
    type: "administrator",
    date: new Date("2025-11-05"),
    openingBalance: 50000,
    status: "open",
    transactions: transactions.filter((t) => t.cashRegisterType === "administrator"),
  },
  {
    id: "cash-prof-1",
    type: "professional",
    professionalId: "prof-1",
    date: new Date("2025-11-05"),
    openingBalance: 0,
    status: "open",
    transactions: transactions.filter((t) => t.professionalId === "prof-1" && t.paymentMethod === "cash"),
  },
  {
    id: "cash-prof-2",
    type: "professional",
    professionalId: "prof-2",
    date: new Date("2025-11-05"),
    openingBalance: 0,
    status: "open",
    transactions: transactions.filter((t) => t.professionalId === "prof-2" && t.paymentMethod === "cash"),
  },
  {
    id: "cash-prof-3",
    type: "professional",
    professionalId: "prof-3",
    date: new Date("2025-11-05"),
    openingBalance: 0,
    status: "open",
    transactions: [],
  },
  {
    id: "cash-reception",
    type: "reception",
    date: new Date("2025-11-05"),
    openingBalance: 5000,
    fixedFund: 5000,
    status: "open",
    transactions: transactions.filter((t) => t.cashRegisterType === "reception"),
  },
]

// For backwards compatibility
export const cashRegister: CashRegister = cashRegisters[0]

export const settlements: Settlement[] = [
  // Liquidación diaria de octubre - Roberto Fernández
  {
    id: "settlement-oct-1",
    professionalId: "prof-1",
    type: "daily",
    totalBilled: 4300,
    professionalEarnings: 2580,
    tenseCommission: 1720,
    status: "paid",
    createdAt: new Date("2025-10-15"),
    paidAt: new Date("2025-10-16"),
  },
  // Liquidación mensual octubre - Roberto Fernández
  {
    id: "settlement-oct-monthly-1",
    professionalId: "prof-1",
    type: "monthly",
    totalBilled: 17200, // 4 turnos de 4300
    professionalEarnings: 10320,
    tenseCommission: 6880,
    status: "paid",
    createdAt: new Date("2025-10-31"),
    paidAt: new Date("2025-11-01"),
  },
]

export const servicePacks: ServicePack[] = [
  {
    id: "pack-1",
    serviceId: "service-2",
    name: "Pack 4 Sesiones Entrenamiento",
    sessionsCount: 4,
    totalPrice: 15000,
    validityDays: 60,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "pack-2",
    serviceId: "service-2",
    name: "Pack 8 Sesiones Entrenamiento",
    sessionsCount: 8,
    totalPrice: 28000,
    validityDays: 90,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "pack-3",
    serviceId: "service-1",
    name: "Pack 4 Sesiones Kinesiología",
    sessionsCount: 4,
    totalPrice: 20000,
    validityDays: 60,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
]

// Keep services export for backwards compatibility
export const services = serviceConfigs.map((s) => ({
  id: s.id,
  name: s.name,
  duration: s.standardDuration,
  price: s.basePrice,
}))
export const medicalRecords: MedicalRecord[] = [
  {
    id: "record-1",
    clientId: "client-1",
    personalData: {
      bloodType: "O+",
      allergies: ["Penicilina"],
      chronicConditions: ["Ninguna"],
      currentMedications: ["Ninguno"],
      emergencyContact: {
        name: "María González",
        phone: "1122334455",
        relationship: "Madre",
      },
    },
    kinesiologyEvaluations: [],
    kinesiologyTreatments: [],
    kineHomePrograms: [],
    trainingEvaluations: [],
    trainingRoutines: [],
    anthropometryEvaluations: [],
    recipes: [],
    nutritionalEducation: [],
    massageEvaluations: [],
    yogaEvaluations: [],
    clinicalEvolutions: [],
    medicalMedia: [],
    patientLogs: [
      {
        id: "log-1",
        clientId: "client-1",
        date: new Date(new Date().setDate(new Date().getDate() - 2)),
        hydration: { amount: 2, unit: "litros", goalReached: true },
        pain: { eva: 4, location: "Lumbares" },
        sleep: { hours: 7, quality: 4, awakenings: false },
        stress: { level: 5 },
        mood: { value: "bueno" },
        activity: { steps: 8000, type: "caminata", duration: 45 },
        nutrition: { description: "Dieta normal", respectedCompliance: true },
        measurements: { weight: 75, height: 180 },
        photos: [],
        createdAt: new Date(),
      },
      {
        id: "log-2",
        clientId: "client-1",
        date: new Date(new Date().setDate(new Date().getDate() - 1)),
        hydration: { amount: 2.5, unit: "litros", goalReached: true },
        pain: { eva: 3, location: "Lumbares" },
        sleep: { hours: 8, quality: 5, awakenings: false },
        stress: { level: 3 },
        mood: { value: "muy_bueno" },
        activity: { steps: 10000, type: "entrenamiento", duration: 60 },
        nutrition: { description: "Respeté indicaciones", respectedCompliance: true },
        measurements: { weight: 74.8 },
        photos: [],
        createdAt: new Date(),
      },
    ],
    patientTasks: [
      {
        id: "task-1",
        clientId: "client-1",
        professionalId: "prof-1",
        title: "Dormir 8 hs durante 7 días",
        description: "Mantener una higiene de sueño constante",
        type: "sueño",
        startDate: new Date(),
        endDate: new Date(new Date().setDate(new Date().getDate() + 7)),
        frequency: "diaria",
        pointsValue: 20,
        status: "pending",
        visibleToPatient: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "task-2",
        clientId: "client-1",
        professionalId: "prof-1",
        title: "Tomar 2 litros de agua",
        description: "Hidratación constante para recuperación celular",
        type: "habitos",
        startDate: new Date(),
        endDate: new Date(new Date().setDate(new Date().getDate() + 30)),
        frequency: "diaria",
        pointsValue: 10,
        status: "pending",
        visibleToPatient: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    progressHistory: [
      { date: new Date(new Date().setDate(new Date().getDate() - 5)), score: 1000, type: "neutral" },
      { date: new Date(new Date().setDate(new Date().getDate() - 4)), score: 1015, event: "Sesión asistida", type: "positive" },
      { date: new Date(new Date().setDate(new Date().getDate() - 3)), score: 1010, event: "Estrés alto", type: "negative" },
      { date: new Date(new Date().setDate(new Date().getDate() - 2)), score: 1025, event: "Registro diario completo", type: "positive" },
      { date: new Date(new Date().setDate(new Date().getDate() - 1)), score: 1040, event: "Registro diario completo", type: "positive" },
    ],
    dailyLogs: [],
    smartObjectives: [],
    achievements: [],
    clinicalDecisions: [],
    activityLogs: [],
    healthStatus: {
      general: "Estable",
      lastCheckup: new Date(),
      alerts: [],
    },
    lastUpdated: new Date(),
    createdAt: new Date(),
    version: 1,
  },
]

export const conversations: ChatConversation[] = [
  {
    id: "chat-1",
    clientId: "client-1",
    professionalId: "prof-1",
    participantIds: ["client-1", "prof-1"],
    participantNames: ["Ramiro González", "Dr. Roberto Fernández"],
    lastMessage: "Excelente Dr. Mañana nos vemos.",
    lastMessageAt: new Date("2026-02-05T09:30:00"),
    unreadCount: 0,
    createdAt: new Date("2026-02-01"),
  },
  {
    id: "chat-2",
    clientId: "client-2",
    professionalId: "prof-2",
    participantIds: ["client-2", "prof-2"],
    participantNames: ["Carla Méndez", "Lic. María Gómez"],
    lastMessage: "¿Podemos cambiar el turno de kine?",
    lastMessageAt: new Date("2026-02-04T18:45:00"),
    unreadCount: 1,
    createdAt: new Date("2026-02-02"),
  },
  {
    id: "chat-3",
    clientId: "client-ana",
    professionalId: "prof-1",
    participantIds: ["client-ana", "prof-1"],
    participantNames: ["Ana Martínez", "Dr. Roberto Fernández"],
    lastMessage: "La rutina está cargada.",
    lastMessageAt: new Date("2026-02-05T11:00:00"),
    unreadCount: 0,
    createdAt: new Date("2026-02-03"),
  },
]

export const chatMessages: ChatMessage[] = [
  // Chat 1: Ramiro & Roberto
  {
    id: "msg-1-1",
    conversationId: "chat-1",
    senderId: "prof-1",
    content: "Hola Ramiro, ¿cómo va esa rodilla hoy?",
    type: "text",
    senderRole: "professional",
    createdAt: new Date("2026-02-05T09:00:00"),
    readBy: ["client-1"],
  },
  {
    id: "msg-1-2",
    conversationId: "chat-1",
    senderId: "client-1",
    content: "Hola Dr! Mucho mejor, ya no me duele al subir escaleras.",
    type: "text",
    senderRole: "client",
    createdAt: new Date("2026-02-05T09:15:00"),
    readBy: ["prof-1"],
  },
  {
    id: "msg-1-3",
    conversationId: "chat-1",
    senderId: "prof-1",
    content: "Excelente noticia. Mañana en la sesión vamos a probar un poco más de carga.",
    type: "text",
    senderRole: "professional",
    createdAt: new Date("2026-02-05T09:25:00"),
    readBy: ["client-1"],
  },
  {
    id: "msg-1-4",
    conversationId: "chat-1",
    senderId: "client-1",
    content: "Excelente Dr. Mañana nos vemos.",
    type: "text",
    senderRole: "client",
    createdAt: new Date("2026-02-05T09:30:00"),
    readBy: ["prof-1"],
  },
  // Chat 2: Carla & Maria
  {
    id: "msg-2-1",
    conversationId: "chat-2",
    senderId: "client-2",
    content: "Lic, ¿le puedo hacer una consulta sobre los ejercicios de ayer?",
    type: "text",
    senderRole: "client",
    createdAt: new Date("2026-02-04T10:00:00"),
    readBy: ["prof-2"],
  },
  {
    id: "msg-2-2",
    conversationId: "chat-2",
    senderId: "prof-2",
    content: "Sí Carla, dime. ¿Sentiste alguna molestia?",
    type: "text",
    senderRole: "professional",
    createdAt: new Date("2026-02-04T10:30:00"),
    readBy: ["client-2"],
  },
  {
    id: "msg-2-3",
    conversationId: "chat-2",
    senderId: "client-2",
    content: "¿Podemos cambiar el turno de kine? Me surgió un imprevisto.",
    type: "text",
    senderRole: "client",
    createdAt: new Date("2026-02-04T18:45:00"),
    readBy: [],
  },
]

export const mockOccupationGoals: StaffGoal[] = [
  {
    id: "goal-1",
    title: "Ocupación Kinesiología",
    description: "Meta de ocupación mensual para el servicio de Kinesiología",
    targetValue: 75,
    currentValue: 0,
    unit: "%",
    startDate: new Date(),
    endDate: new Date(),
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "goal-2",
    title: "Ocupación Entrenamiento",
    description: "Meta de ocupación mensual para Entrenamiento Personalizado",
    targetValue: 80,
    currentValue: 0,
    unit: "%",
    startDate: new Date(),
    endDate: new Date(),
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]
